import { useEffect, useState } from "react";
import { getLimits, getTransactions } from "../db/budgetDB";

const money = (value) => `${Number(value || 0).toLocaleString("pl-PL", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} zł`;
const localDate = (date) => new Date(date).toLocaleDateString("sv-SE");

export default function Home() {
  const [summary, setSummary] = useState({ income: 0, month: 0, today: 0, week: 0, all: 0 }); const [alerts, setAlerts] = useState([]);
  useEffect(() => { async function load() { const [data, limits] = await Promise.all([getTransactions(), getLimits()]); const today = new Date(); const currentMonth = today.toISOString().slice(0, 7); const weekStart = new Date(today); weekStart.setDate(today.getDate() - ((today.getDay() + 6) % 7)); weekStart.setHours(0, 0, 0, 0); const expenses = data.filter((item) => item.type === "expense"); const amount = (items) => items.reduce((sum, item) => sum + Number(item.amount || 0), 0); const monthly = expenses.filter((item) => item.month === currentMonth); const byCategory = {}; monthly.forEach((item) => { const key = item.category || "Inne"; byCategory[key] = (byCategory[key] || 0) + Number(item.amount || 0); }); setSummary({ income: amount(data.filter((item) => item.type === "income" && item.month === currentMonth)), month: amount(monthly), today: amount(expenses.filter((item) => localDate(item.date || `${item.month}-01`) === localDate(today))), week: amount(expenses.filter((item) => new Date(item.date || `${item.month}-01`) >= weekStart && new Date(item.date || `${item.month}-01`) <= today)), all: amount(expenses) }); setAlerts(limits.filter((limit) => limit.amount > 0 && byCategory[limit.category] > limit.amount).map((limit) => ({ category: limit.category, over: byCategory[limit.category] - limit.amount }))); } load(); }, []);
  const balance = summary.income - summary.month;
  return <div className="screen"><h1>BUDŻET</h1><div className="wealth-card"><div className="wealth-title">BILANS BIEŻĄCEGO MIESIĄCA</div><div className="wealth-value">{money(balance)}</div><div className="wealth-grid"><div className="wealth-item"><div className="wealth-label">Dochody</div><div className="wealth-number">{money(summary.income)}</div></div><div className="wealth-item"><div className="wealth-label">Wydatki</div><div className="wealth-number">{money(summary.month)}</div></div></div></div><h2 className="section-title">Wydatki</h2><div className="overview-grid"><div className="summary-box"><small>Dzisiaj</small><strong>{money(summary.today)}</strong></div><div className="summary-box"><small>Ten tydzień</small><strong>{money(summary.week)}</strong></div><div className="summary-box"><small>Ten miesiąc</small><strong>{money(summary.month)}</strong></div><div className="summary-box"><small>Wszystkie</small><strong>{money(summary.all)}</strong></div></div>{alerts.map((alert) => <div className="budget-alert" key={alert.category}>Przekroczono miesięczny limit w kategorii {alert.category} o {money(alert.over)}.</div>)}</div>;
}
