import { useEffect, useState } from "react";
import { getLimits, getTransactions } from "../db/budgetDB";
import { localMonth } from "../utils/date";

const money = (value) => `${Number(value || 0).toLocaleString("pl-PL", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} zł`;
const localDate = (date) => new Date(date).toLocaleDateString("sv-SE");

export default function Home() {
  const [summary, setSummary] = useState({ income: 0, month: 0, today: 0, week: 0, all: 0, investments: 0, limits: [] });
  useEffect(() => { async function load() { const [data, limits] = await Promise.all([getTransactions(), getLimits()]); const today = new Date(); const currentMonth = localMonth(today); const weekStart = new Date(today); weekStart.setDate(today.getDate() - ((today.getDay() + 6) % 7)); weekStart.setHours(0, 0, 0, 0); const expenses = data.filter((item) => item.type === "expense"); const amount = (items) => items.reduce((sum, item) => sum + Number(item.amount || 0), 0); const monthly = expenses.filter((item) => item.month === currentMonth); const investments = monthly.filter((item) => item.subtype === "investment" || item.category === "Inwestycje"); const byCategory = {}; monthly.forEach((item) => { const key = item.category || "Inne"; byCategory[key] = (byCategory[key] || 0) + Number(item.amount || 0); }); setSummary({ income: amount(data.filter((item) => item.type === "income" && item.month === currentMonth)), month: amount(monthly), today: amount(expenses.filter((item) => localDate(item.date || `${item.month}-01`) === localDate(today))), week: amount(expenses.filter((item) => { const date = new Date(item.date || `${item.month}-01`); return date >= weekStart && date <= today; })), all: amount(expenses), investments: amount(investments), limits: limits.filter((limit) => limit.amount && (byCategory[limit.category] || 0) >= limit.amount * 0.8).map((limit) => ({ ...limit, used: byCategory[limit.category] || 0 })) }); } load(); }, []);
  const balance = summary.income - summary.month; const investments = summary.investments || 0; const saved = balance + investments; const percent = summary.income > 0 ? Math.max(0, Math.min(100, (saved / summary.income) * 100)) : 0;
  return <div className="screen home-screen"><h1>Budżet</h1><div className="wealth-card"><div className="wealth-title">Bilans bieżącego miesiąca</div><div className="wealth-value">{money(balance)}</div><div className="wealth-grid"><div className="wealth-item"><div className="wealth-label">Dochody</div><div className="wealth-number">{money(summary.income)}</div></div><div className="wealth-item"><div className="wealth-label">Wydatki</div><div className="wealth-number">{money(summary.month)}</div></div></div><div className="remaining"><span>Zaoszczędzone środki</span><strong>{money(saved)}</strong><small>W tym inwestycje: {money(investments)}</small><div className="progress"><div className="progress-fill" style={{ width: `${percent}%` }} /></div><small>{percent.toFixed(0)}% dochodów przeznaczonych na oszczędności</small></div></div><h2 className="section-title">Wydatki</h2><div className="overview-grid"><div className="summary-box"><small>Dzisiaj</small><strong>{money(summary.today)}</strong></div><div className="summary-box"><small>Ten tydzień</small><strong>{money(summary.week)}</strong></div><div className="summary-box"><small>Ten miesiąc</small><strong>{money(summary.month)}</strong></div><div className="summary-box"><small>Wszystkie</small><strong>{money(summary.all)}</strong></div></div>{summary.limits.map((limit) => <article className="home-limit" key={limit.category}><strong>⚠ {limit.category}</strong><span>{money(limit.used)} / {money(limit.amount)}</span><div className="progress"><div className={limit.used > limit.amount ? "progress-fill danger-fill" : "progress-fill"} style={{ width: `${Math.min(100, limit.used / limit.amount * 100)}%` }} /></div><small>{limit.used > limit.amount ? `Przekroczono o ${money(limit.used - limit.amount)}` : `Pozostało ${money(limit.amount - limit.used)}`}</small></article>)}</div>;
}
