import { useEffect, useState } from "react";
import { FaChartLine, FaReceipt, FaStore, FaWallet } from "react-icons/fa";
import MonthSelector from "../components/MonthSelector";
import ExpenseChartPremium from "../components/ExpenseChartPremium";
import { getTransactions } from "../db/budgetDB";
import { localMonth } from "../utils/date";

const money = (value) => `${Number(value || 0).toLocaleString("pl-PL", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} zł`;
export default function Summary() {
  const [month, setMonth] = useState(localMonth()); const [data, setData] = useState({ income: 0, expense: 0, chart: [], count: 0, biggest: 0, shop: "—" });
  useEffect(() => { async function load() { const items = (await getTransactions()).filter((item) => item.month === month); const expenses = items.filter((item) => item.type === "expense"); const income = items.filter((item) => item.type === "income").reduce((sum, item) => sum + Number(item.amount || 0), 0); const grouped = {}; const shops = {}; expenses.forEach((item) => { const category = item.category || "Inne"; grouped[category] = (grouped[category] || 0) + Number(item.amount || 0); shops[item.title] = (shops[item.title] || 0) + 1; }); const frequent = Object.entries(shops).sort(([, a], [, b]) => b - a)[0]?.[0] || "—"; setData({ income, expense: expenses.reduce((sum, item) => sum + Number(item.amount || 0), 0), chart: Object.entries(grouped).map(([name, value]) => ({ name, value })), count: expenses.length, biggest: Math.max(0, ...expenses.map((item) => Number(item.amount || 0))), shop: frequent }); } load(); }, [month]);
  const days = month === localMonth() ? new Date().getDate() : new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate(); const top = [...data.chart].sort((a, b) => b.value - a.value).slice(0, 5); const max = top[0]?.value || 1;
  const insights = [{ icon: <FaChartLine />, label: "Średnio dziennie", value: money(data.expense / days) }, { icon: <FaWallet />, label: "Największy wydatek", value: money(data.biggest) }, { icon: <FaReceipt />, label: "Transakcje", value: data.count }, { icon: <FaWallet />, label: "Śr. koszt transakcji", value: money(data.count ? data.expense / data.count : 0) }, { icon: <FaStore />, label: "Najczęstszy sklep", value: data.shop }];
  return <div className="screen stats-screen"><h1>Statystyki</h1><MonthSelector month={month} setMonth={setMonth} /><div className="stats-main"><div><small>Dochody</small><strong>{money(data.income)}</strong></div><div><small>Wydatki</small><strong>{money(data.expense)}</strong></div><div><small>Bilans</small><strong>{money(data.income - data.expense)}</strong></div></div><ExpenseChartPremium data={data.chart} /><section className="insights-section"><div className="section-header"><span className="eyebrow">NAJWAŻNIEJSZE LICZBY</span><h2>Podsumowanie miesiąca</h2></div><div className="insight-grid">{insights.map((item) => <article key={item.label}><span className="insight-icon">{item.icon}</span><small>{item.label}</small><strong>{item.value}</strong></article>)}</div></section><section className="top-categories"><div className="section-header"><span className="eyebrow">NAJWIĘKSZE OBCIĄŻENIA</span><h2>TOP 5 kategorii</h2></div>{top.map((item) => <div className="top-category" key={item.name}><div><span>{item.name}</span><strong>{money(item.value)}</strong></div><div className="progress"><div className="progress-fill" style={{ width: `${(item.value / max) * 100}%` }} /></div></div>)}</section></div>;
}
