import { useEffect, useState } from "react";
import MonthSelector from "../components/MonthSelector";
import ExpenseChartPremium from "../components/ExpenseChartPremium";
import { getTransactions } from "../db/budgetDB";
const money = (value) => `${Number(value || 0).toLocaleString("pl-PL", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} zł`;
export default function Summary() {
  const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [data, setData] = useState({ income: 0, expense: 0, chart: [], count: 0, biggest: 0, shop: "—" });
  useEffect(() => { async function load() { const items = (await getTransactions()).filter((item) => item.month === month); const expenses = items.filter((item) => item.type === "expense"); const income = items.filter((item) => item.type === "income").reduce((sum, item) => sum + Number(item.amount || 0), 0); const grouped = {}; const shops = {}; expenses.forEach((item) => { const category = item.category || "Inne"; grouped[category] = (grouped[category] || 0) + Number(item.amount || 0); shops[item.title] = (shops[item.title] || 0) + 1; }); const frequent = Object.entries(shops).sort(([, a], [, b]) => b - a)[0]?.[0] || "—"; setData({ income, expense: expenses.reduce((sum, item) => sum + Number(item.amount || 0), 0), chart: Object.entries(grouped).map(([name, value]) => ({ name, value })), count: expenses.length, biggest: Math.max(0, ...expenses.map((item) => Number(item.amount || 0))), shop: frequent }); } load(); }, [month]);
  const days = new Date(`${month}-01`).getMonth() === new Date().getMonth() && month.slice(0, 4) === String(new Date().getFullYear()) ? new Date().getDate() : new Date(Number(month.slice(0, 4)), Number(month.slice(5)), 0).getDate();
  const top = [...data.chart].sort((a, b) => b.value - a.value).slice(0, 5); const max = top[0]?.value || 1;
  return <div className="screen"><h1>Statystyki</h1><MonthSelector month={month} setMonth={setMonth} /><div className="stats-main"><div><small>Dochody</small><strong>{money(data.income)}</strong></div><div><small>Wydatki</small><strong>{money(data.expense)}</strong></div><div><small>Bilans</small><strong>{money(data.income - data.expense)}</strong></div></div><ExpenseChartPremium data={data.chart} /><section className="insight-grid"><div><small>Średnio dziennie</small><strong>{money(data.expense / days)}</strong></div><div><small>Największy wydatek</small><strong>{money(data.biggest)}</strong></div><div><small>Transakcje</small><strong>{data.count}</strong></div><div><small>Śr. koszt transakcji</small><strong>{money(data.count ? data.expense / data.count : 0)}</strong></div><div><small>Najczęstszy sklep</small><strong>{data.shop}</strong></div></section><section className="top-categories"><h2>TOP 5 kategorii</h2>{top.map((item) => <div className="top-category" key={item.name}><div><span>{item.name}</span><strong>{money(item.value)}</strong></div><div className="progress"><div className="progress-fill" style={{ width: `${(item.value / max) * 100}%` }} /></div></div>)}</section></div>;
}
